# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  workflow_dispatch:
  push:
    branches: [ samer ]
  pull_request:
    branches: [ samer ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml

  Deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: fetch code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - name: deploy
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.STAGING_SERVER_IP }}
          username: ${{ secrets.STAGING_SERVER_DEPLOY_USR }}
          key: ${{ secrets.STAGING_SERVER_KEY }}
          source: "target/PPU2-1.0.jar"
          target: "deployment"
      - name: run jar via ssh
        uses: fifsky/ssh-action@master
        with:
          command: |
            cd ~/deployment/target
            java -jar PPU2-1.0.jar
          host: ${{ secrets.STAGING_SERVER_IP }}
          user: ${{ secrets.STAGING_SERVER_DEPLOY_USR }}
          key: ${{ secrets.STAGING_SERVER_KEY }}
